name: Release
run-name:
  ${{ inputs.type }} - dry-run:${{ inputs.dry-run }} by @${{ github.actor }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        description: 'Specify the type of release'
        type: choice
        default: first minor rc
        options:
          - full minor release
          - first minor rc
          - full patch release
          - first patch rc
          - subsequent rc
      dry-run:
        required: true
        default: true
        description: 'Run dry-run'
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: |
      github.repository == 'carbon-design-system/carbon-for-ai'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: '0'
      - run: |
          git config user.name carbon-bot
          git config user.email carbon@us.ibm.com
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build

      - name: Publish releases with dry run
        run: |
          if [[ ${{ github.event.inputs.dry-run == 'true' }} && ${{github.event.inputs.type == 'full minor release' }} ]]; then
            pnpm lerna publish minor --conventional-graduate
          elif [[ ${{ github.event.inputs.dry-run == 'true' }} && ${{github.event.inputs.type == 'first minor rc' }} ]]; then
            pnpm lerna publish preminor --conventional-prerelease --preid rc --pre-dist-tag next
          elif [[ ${{ github.event.inputs.dry-run == 'true' }} && ${{github.event.inputs.type == 'full patch release' }} ]]; then
            pnpm lerna publish patch --conventional-graduate
          elif [[ ${{ github.event.inputs.dry-run == 'true' }} && ${{github.event.inputs.type == 'first patch rc' }} ]]; then
            pnpm lerna publish prepatch --conventional-prerelease --preid rc --pre-dist-tag next
          elif [[ ${{ github.event.inputs.dry-run == 'true' }} && ${{github.event.inputs.type == 'subsequent rc' }} ]]; then
            pnpm lerna publish --conventional-prerelease --preid rc --pre-dist-tag next
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
